name: Generate and Commit ASCII Art PNG

on:
  push:
    branches:
      - main  # 対象ブランチ（必要に応じて変更）

jobs:
  ascii-art:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pillow

      - name: Run ASCII Art Generator
        run: python ascii_art.py

      - name: Commit generated ASCII art PNG
        uses: EndBug/add-and-commit@v9
        with:
          add: 'ascii_art.png'
          message: 'Update ASCII art PNG'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
